### ISSUE TITLE
progress & threshold

### ISSUE THREAD

**Issue by jsonkao** [jsonkao/react-scrollama#1]
fire incremental step progress update

**Comment by allan-walker** [comment]
@jsonkao 

Hey man, love the work! How would you suggest I go about implementing this feature, I'm working on a project at the moment that could use it. Just interested to know if you had any thoughts before I got stuck in. 

Thanks! Al

**Comment by jsonkao** [comment]
Thanks so much! The good news is that the Intersection Observer API has thresholds built in. Here is a small excerpt from [the documentation](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API):
> **threshold**: Either a single number or an array of numbers which indicate at what percentage of the target's visibility the observer's callback should be executed...

If you need any help, definitely reach out on this thread. Also, feel free to open a pull request after you're done!
