### ISSUE TITLE
Dynamic contents don't get updated

### ISSUE THREAD

**Issue by fabioasdias** [jsonkao/react-scrollama#10]
Relevalent snippet

```javascript
let jsx=[];
for (let i=0;i<N;i++){
   jsx.push(<Step data={{step:i}}><div> {i}</div></Step>);
}
return(<Scrollama onStepEnter={onStepEnter}>{jsx}</Scrollama>);

```

This works well while N is the same (or smaller) than the original. But if you change N to a larger number afterwards, it will only work up to that number.

**Comment by jsonkao** [comment]
Thank your for submitting an issue! I've replicated the problem on my end; working on it now.

**Comment by jsonkao** [comment]
Hi @fabioasdias, the fix is mostly completed. I am in the process of reviewing/merging the new code. Expect a release tomorrow.

**Comment by jsonkao** [comment]
Merged! Thanks again for submitting this feature.
