### ISSUE TITLE
Scroll direction up not working on Android Chrome

### ISSUE THREAD

**Issue by angelozehr** [jsonkao/react-scrollama#16]
On different Android Smartphones that I have tested (e.g. Samsung Galaxy S7 with Android Version 8.0.0 and Chrome Version 73.0.3683.90) scrolling upwards does not trigger anything.

I made a video. Sometimes the step get's triggered, but most of the time it does not:
<https://youtu.be/wqNRNE2ZSF4>

**Comment by jsonkao** [comment]
Hi @angelozehr, thanks for filing an issue! Yesterday, I released v1 of `react-scrollama`, rewriting most of its internals. Could you check again to see if the bug still exists?

**Comment by michaelgrotton** [comment]
Hey, I tried this out and it still doesn't work for me on Android Chrome, but it looks it may be an issue with the original library? https://github.com/russellgoldenberg/scrollama/issues/87

**Comment by GitNoise** [comment]
@michaelgrotton How did you include the polyfill? I know that the original scrollama uses the polyfill in their demos but I am not sure how to add it using react.

**Comment by jsonkao** [comment]
Note: As of version 2.2.0, the [IntersectionObserver polyfill](https://www.npmjs.com/package/intersection-observer) has been removed from the build. You must include it yourself for cross-browser support. [Check here](https://caniuse.com/#feat=intersectionobserver) to see if you need to include the polyfill.

You can install the polyfill like so:
```
$ npm install intersection-observer
```

And just import or require the polyfill somewhere. Not sure if it has to be imported before other modules.
