### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by cedricdelpoux** [jsonkao/react-scrollama#38]
When building a Gatsby site (using Server Side Rendering) I got this error:
```
ReferenceError: regeneratorRuntime is not defined
node_modules/react-scrollama/dist/index.es.js:594:1
```

**Comment by jsonkao** [comment]
I think this error can be resolved by removing old/unnecessary async/await code.

**Comment by jsonkao** [comment]
@cedricdelpoux this is fixed in [`react-scrollama@2.2.7`](https://www.npmjs.com/package/react-scrollama).

**Comment by cedricdelpoux** [comment]
Thank you for helping 👏🏻 You are very fast 🚀

**Comment by jsonkao** [comment]
No problem :)
