### ISSUE TITLE
"window" is not available during server side rendering

### ISSUE THREAD

**Issue by cedricdelpoux** [jsonkao/react-scrollama#59]
Hi, the last version `2.2.13` is not compatible with server side rendering

error occurs when calling `window.innerHeight`.

I need to downgrade to version `2.2.7` to make `react-scrollama` work with SSR

**Comment by jsonkao** [comment]
Hey, sorry about that. Do you have suggestions about how to check for SSR/functionally fix this?

**Comment by cedricdelpoux** [comment]
I think it juste a one line check because there is only one `window` during initialisation.
I made a PR

**Comment by jsonkao** [comment]
And just to make sure, a default value of 0 wouldn't break any functionality/introduce weird bugs right?

**Comment by cedricdelpoux** [comment]
It does not change anything for user who don't use SSR
