### ISSUE TITLE
Update peerDependencies - allow React 17 and 18

### ISSUE THREAD

**Issue by jkjustjoshing** [jsonkao/react-scrollama#67]
Right now, the versions of `react` and `react-dom` required are [^16.8.0](https://github.com/jsonkao/react-scrollama/blob/master/package.json#L37). However, this library should work fine with React 17 and React 18 (both of which are allowed in the [react-intersection-observer dependency](https://github.com/thebuilder/react-intersection-observer/blob/master/package.json#L131).

NPM v8 is enforcing peerDependencies more strictly than previous versions, so trying to install this on a React 17 project errors. I don't think there's anything in the library that would preclude it from working on newer versions of React. Can we add those versions to this package's peer dependencies?

**Comment by jsonkao** [comment]
Thanks for letting me know! Yes, this should be fine. Wanna submit a PR?

**Comment by RSS1102** [comment]
`react` and  `react-dom`： ^18.xx now,may be should update it. v_v

**Comment by jsonkao** [comment]
Yup #90 adds React 18 - just published a new release of the library - 2.3.2. Thanks for pointing this out yall!
