### ISSUE TITLE
 Failed to construct 'IntersectionObserver'

### ISSUE THREAD

**Issue by rl627** [jsonkao/react-scrollama#74]
Example code throws this error:

**SyntaxError: Failed to construct 'IntersectionObserver': rootMargin must be specified in pixels or percent.**

**Comment by robhawkes** [comment]
You can resolve this by setting an `offset`:

```javascript
<Scrollama offset={0.5}>
  ...
</Scrollama>
```

**Comment by jsonkao** [comment]
Thank you @rl627 for bringing this to our attention and @robhawkes for providing the answer. I'll change the documentation now!

![selfie-0](https://i.imgur.com/KFtlEw9.jpg)
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)
