### ISSUE TITLE
Forgot default Props for offset in Scrollama.js

### ISSUE THREAD

**Issue by fschwander** [jsonkao/react-scrollama#88]
Hey there!

First of all: thanks for the great npm package. <3

It seems that you forgot the default props of of offset equals 0.3 in Scrollama.js (as described in your documentation). 

Best, Fabian

**Comment by jsonkao** [comment]
![selfie-0](https://i.imgur.com/pZNGI2Q.gif)
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)
